### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by Russ93** [devfacet/mws-product#3]
``` javascript
var async = require("async");
ASINs = [ 'B00CHUYT0I',
    'B00J38B6XK',
    'B00CJKT3B6',
    'B005XWG3II',
    'B00IQVH7I8',
    'B0049CTYNE',
    'B0094QUGBY',
    'B00E2HOE8G',
    'B00C1PWAD2',
    'B006H9JVVM',
    'B00IUYN3CA',
    'B004ASA47C',
    'B00CIY615E',
    'B00CJMSOCS',
    'B00AA9O3LS',
    'B00A8MVQO4',
    'B002EYNC3M',
    'B00IQVERRC',
    'B00J389J34',
    'B00CHVXUW0' ]

async.whilst(
    function(){ return true; },
    function(done){ mwsProducts.myPriceForASIN({'asinList': ASINs}, done); }
)
```

let this run for a little while and watch your memory usage climb
I love this module and use it very often I will be looking into the issue to hopefully find it but I was wondering if you had the same issue

**Comment by cmfatih** [comment]
@Russ93 : honestly I haven't used it for so long. Can you take [heapdump](https://www.npmjs.com/package/heapdump) before run and after run then compress it and try to upload here. I can check for you what's going on. Or you can check yourself https://www.npmjs.com/package/heapdump#inspecting-the-snapshot

**Comment by Russ93** [comment]
tough-cookie is holding too much
I'm not sure how to export only certain result this has a lot of sensitive information

**Comment by cmfatih** [comment]
@Russ93 : Well you can try to determine that memory leak yourself - See http://davidwalsh.name/reducing-memory-leaks-working-animations
